### ISSUE TITLE
module 'pixie' has no attribute 'PK_SOLID'

### ISSUE THREAD

**Issue by ZaneHuangPro** [treeform/pixie-python#22]
This is the source code：
```
import pixie

image = pixie.Image(200, 200)
image.fill(pixie.Color(1, 1, 1, 1))

paint = pixie.Paint(pixie.PK_SOLID)
paint.color = pixie.Color(1, 0, 0, 1)

ctx = image.new_context()
ctx.fill_style = paint

ctx.fill_rect(50, 50, 100, 100)

image.write_file("examples/square.png")
```

I got the following results：
Traceback (most recent call last):
  File "F:\Python\Python Project\Test\test.py", line 6, in <module>
    paint = pixie.Paint(pixie.PK_SOLID)
AttributeError: module 'pixie' has no attribute 'PK_SOLID'

**Comment by guzba** [comment]
Hello, we updated the Paint enumeration names so you'll want to use `pixie.SOLID_PAINT` now instead of `pixie.PK_SOLID`.
